compilerOptions:
  # emittance
  outDir: '{output}'
  module: commonjs # node doesn't support anything non commonjs code yet
  target: ES2017 # use ES2017 as it's the latest standard node 10 can be fully compatible with
  declaration: true
  inlineSourceMap: true

  # compatibility
  allowSyntheticDefaultImports: true
  esModuleInterop: true
  experimentalDecorators: true
  emitDecoratorMetadata: true
  isolatedModules: false
  jsx: react-jsx

  # module resolution
  moduleResolution: node
  resolveJsonModule: true
  baseUrl: .
  paths:
    '#*':
      - '{source}/*'
    '*':
      - '{types}/*'

  # libraries
  lib:
    - ES2020
    - ESNext
    - DOM
    - DOM.Iterable
include:
  - '**/*.json'
  - '**/*.ts'
  - '**/*.tsx'
exclude:
  - '**/node_modules'
