name: code coverage

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use node lts
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: install code climate reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
          chmod +x /tmp/cc-test-reporter
      - name: cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('pnpm-lock.yaml') }}
      - name: enable corepack
        run: corepack enable
      - name: install dependencies
        run: pnpm install
      - name: run coverage
        run: pnpm run coverage
        env:
          CI: true
      - name: upload coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          for f in packages/*; do
            if [ -d "$f" ]; then
              echo $f
              if [ -d "$f/coverage" ]; then
                /tmp/cc-test-reporter format-coverage -t lcov -o coverage.${f//\//-}.json $f/coverage/lcov.info
              fi
            fi
          done;
          /tmp/cc-test-reporter sum-coverage -o coverage.total.json coverage.*.json
          /tmp/cc-test-reporter upload-coverage -i coverage.total.json