name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: publish the release note
        run: npx github-release-from-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: login to npm
        run: npm config set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: publish the package
        run: npm publish --workspaces --verbose
