name: code style

on:
  push:
    branches:
      - '**'
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use node lts
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: install dependencies
        run: npm ci
      - name: run code style check
        run: npm run lint --if-present
        env:
          CI: true