name: code style

on:
  push:
    branches:
      - '**'
jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install npm@7 for workspace
        run: npm i -g npm@7
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-dependencies-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: run code style check
        run: npm run lint --if-present
        env:
          CI: true